import fs from 'fs';
import path from 'path';
import restData from './restcountries.json';
import { countries } from '../src/data/countries';

const normalize = (value: string) => value
  .toLowerCase()
  .normalize('NFD')
  .replace(/[^a-z0-9]/g, '');

type RestCountry = {
  name: { common: string; official: string };
  altSpellings?: string[];
  translations?: Record<string, { common?: string }>;
};

const index = new Map<string, RestCountry>();
(restData as RestCountry[]).forEach((rc) => {
  const names = [rc.name.common, rc.name.official, ...(rc.altSpellings || [])];
  names.forEach((n) => index.set(normalize(n), rc));
});

const countryNameMap: Record<string, string> = {};
const missing: string[] = [];

countries.forEach((c) => {
  const key = normalize(c.name);
  const match = index.get(key);
  if (match?.translations?.por?.common) {
    countryNameMap[c.id] = match.translations.por.common;
  } else {
    missing.push(c.name);
  }
});

// Portuguese exonyms for capitals (fallback to English when absent)
const capitalOverrides: Record<string, string> = {
  'Rome': 'Roma',
  'London': 'Londres',
  'Vienna': 'Viena',
  'Prague': 'Praga',
  'Warsaw': 'Varsóvia',
  'Brussels': 'Bruxelas',
  'Athens': 'Atenas',
  'Moscow': 'Moscou',
  'Beijing': 'Pequim',
  'Lisbon': 'Lisboa',
  'Berlin': 'Berlim',
  'Bucharest': 'Bucareste',
  'Budapest': 'Budapeste',
  'Copenhagen': 'Copenhague',
  'Stockholm': 'Estocolmo',
  'Helsinki': 'Helsínquia',
  'Belgrade': 'Belgrado',
  'Mexico City': 'Cidade do México',
  'Bangkok': 'Banguecoque',
  'Riyadh': 'Riade',
  'Tehran': 'Teerã',
  'Baghdad': 'Bagdá',
  'Damascus': 'Damasco',
  'Jerusalem': 'Jerusalém',
  'Kuwait City': 'Cidade do Kuwait',
  'Port of Spain': 'Porto de Espanha',
  'Panama City': 'Cidade do Panamá',
  'Guatemala City': 'Cidade da Guatemala',
  'San Jose': 'São José',
  'San José': 'São José',
  'Port-au-Prince': 'Porto Príncipe',
  'New Delhi': 'Nova Deli',
  'Seoul': 'Seul',
  'Pyongyang': 'Pionguiangue',
  'Algiers': 'Argel',
  'Nairobi': 'Nairóbi',
  'Tirana': 'Tirana',
  'Hanoi': 'Hanói',
  'Vientiane': 'Vienciana',
  'Rabat': 'Rabat',
};

const capitalMap: Record<string, string> = {};

countries.forEach((c) => {
  const override = capitalOverrides[c.capital];
  if (override) {
    capitalMap[c.id] = override;
  } else {
    capitalMap[c.id] = c.capital;
  }
});

const outPath = path.join(process.cwd(), 'src/data/ptLocalizations.ts');
const header = `// Auto-generated Portuguese localizations for country names and capitals\n// Generated by scripts/generate-pt-localizations.ts\n// Do not edit manually; update the script instead.\n\nexport const ptCountryNames: Record<string, string> = `;
fs.writeFileSync(
  outPath,
  `${header}${JSON.stringify(countryNameMap, null, 2)} as const;\n\nexport const ptCapitalNames: Record<string, string> = ${JSON.stringify(capitalMap, null, 2)} as const;\n`
);

console.log(`Portuguese name map entries: ${Object.keys(countryNameMap).length}`);
console.log(`Capital overrides applied: ${Object.keys(capitalOverrides).length}`);
if (missing.length) {
  console.warn(`Missing Portuguese names for ${missing.length} countries:`, missing.slice(0, 10));
}
