// This file is auto-generated by scripts/generate-flag-conflicts.ts
// Do not edit manually.
//
// Why: Some territories share the same flag SVG in our current source set, which
// makes the flag quiz ambiguous (multiple correct answers for one image).

export type FlagConflictGroup = {
  sha256: string;
  countryIds: string[];
};

export const FLAG_CONFLICT_GROUPS: FlagConflictGroup[] = [
  {
    "sha256": "9761819bc2d4861e9aba5f76a0a048cf46d44c15fa46ec8a51d92d774c192112",
    "countryIds": [
      "guadeloupe",
      "mayotte",
      "r-union",
      "saint-martin",
      "saint-pierre-and-miquelon"
    ]
  },
  {
    "sha256": "76b13820600bdcd0dab2414235e1aaea71cb14743b59e7548cf451213a906cd7",
    "countryIds": [
      "france",
      "martinique",
      "saint-barth-lemy",
      "wallis-and-futuna"
    ]
  },
  {
    "sha256": "26b91b277d9c69908b8c6bbac0126f178155aed86a5784f2c88431b25f4b327a",
    "countryIds": [
      "bouvet-island",
      "norway",
      "svalbard-and-jan-mayen"
    ]
  },
  {
    "sha256": "9d3bb8c2dea95375c3fb5fb8efa178481ace4113b30fa2884c78bf463d24e258",
    "countryIds": [
      "saint-helena-ascension-and-tristan-da-cunha",
      "united-kingdom"
    ]
  },
  {
    "sha256": "a6333fbc019a8954fb44bdcb95e8358de103358b04475338903e21a67a7d7370",
    "countryIds": [
      "caribbean-netherlands",
      "netherlands"
    ]
  },
  {
    "sha256": "e01f0d187a610548a3124cf26b88b81df977a77a6dceb10ae78fa7b1ccb3824e",
    "countryIds": [
      "australia",
      "heard-island-and-mcdonald-islands"
    ]
  },
  {
    "sha256": "ecc72e4a5a5e366271df24c3a79fa468d10ac4b5edc2896b95b02d95b114336a",
    "countryIds": [
      "united-states",
      "united-states-minor-outlying-islands"
    ]
  }
];

export const FLAG_CONFLICT_COUNTRY_IDS = new Set<string>(
  FLAG_CONFLICT_GROUPS.flatMap((g) => g.countryIds)
);

// Flag-mode policy (simplest): exclude all non-anchor duplicates globally.
// - If a group includes any non-('super_hard'|'god_mode') country, keep the highest-population entry.
// - If a group is only 'super_hard'/'god_mode' entries, exclude the entire group (usually placeholder flags).
export const FLAG_MODE_EXCLUDED_COUNTRY_IDS = new Set<string>([
  "bouvet-island",
  "caribbean-netherlands",
  "guadeloupe",
  "heard-island-and-mcdonald-islands",
  "martinique",
  "mayotte",
  "r-union",
  "saint-barth-lemy",
  "saint-helena-ascension-and-tristan-da-cunha",
  "saint-martin",
  "saint-pierre-and-miquelon",
  "svalbard-and-jan-mayen",
  "united-states-minor-outlying-islands",
  "wallis-and-futuna"
]);
